routes:
  - id: deepseek-chat
    match:
      model: deepseek-chat
    strategy: weight
    target:
      provider: deepseek-main
      model: deepseek-reasoner
    targets:
      - provider: deepseek-main
        model: deepseek-chat
        priority: 1
        weight: 3
      - provider: ollama-local
        model: qwen2.5:0.5b
        priority: 1
        weight: 1

  - id: deepseek-reasoner
    match:
      model: deepseek-reasoner
    target:
      provider: deepseek-main
      model: deepseek-reasoner

  - id: ollama-qwen
    match:
      model: qwen2.5:0.5b
    strategy: priority
    targets:
      - provider: ollama-local
        model: qwen2.5:0.5b
        priority: 1
        weight: 1
